# Generated by Django 5.2.12 on 2026-03-26 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=255)),
                ('position', models.CharField(max_length=255)),
                ('recruiter_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('intro_name', models.CharField(blank=True, max_length=100, null=True)),
                ('job_link', models.URLField(blank=True, max_length=1000, null=True)),
                ('job_description', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('generated_email', models.TextField(blank=True, null=True)),
                ('date_applied', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('applied', 'Applied'), ('interview', 'Interviewing'), ('rejected', 'Rejected'), ('no_response', 'No Response'), ('offer', 'Offer')], default='pending', max_length=20)),
                ('source', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JobDiscoveryResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=255)),
                ('position', models.CharField(max_length=255)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('salary', models.CharField(blank=True, max_length=255, null=True)),
                ('link', models.URLField(blank=True, max_length=1000, null=True)),
                ('source', models.CharField(max_length=50)),
                ('snippet', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
